/*

 Source Server         : LLDB
 Source Server Type    : MySQL
 Source Server Version : 80022
 Source Host           : localhost:3306
 Source Schema         : framedb_1.1

 Target Server Type    : MySQL
 Target Server Version : 80022
 File Encoding         : 65001

 Date: 13/10/2025 16:08:47
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for BASE_USER
-- ----------------------------
DROP TABLE IF EXISTS `BASE_USER`;
CREATE TABLE `BASE_USER`  (
  `USER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户ID',
  `XZQH_ID` bigint(0) NULL DEFAULT NULL COMMENT '行政区划编号，用户来源地',
  `SOURCE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '创建来源类型，身份源ID',
  `CREATE_TYPE` int(0) NULL DEFAULT 1 COMMENT '创建方式，数据来源：0导入1录入2授权',
  `USERNAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户名，城市APP的用户名',
  `MOBILE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '手机号码',
  `EMAIL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '电子邮箱',
  `PASSWORD` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '密码',
  `SALT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '混淆字符',
  `SRC_CODE` int(0) NOT NULL DEFAULT 1 COMMENT '当前来源0缺省1:WEB或PC,2APP21:AndroidAPP,22:IOSAPP,3WAP,4MINI',
  `REGISTER_TIME` datetime(0) NOT NULL COMMENT '注册时间',
  `REGISTER_IP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '127.0.0.1' COMMENT '注册IP',
  `LOGIN_COUNT` int(0) NOT NULL DEFAULT 0 COMMENT '登录次数',
  `CURRENT_LOGIN_TIME` datetime(0) NULL DEFAULT NULL COMMENT '当前登录时间',
  `CURRENT_LOGIN_IP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '127.0.0.1' COMMENT '当前登录IP',
  `LAST_APP_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '最后登录的应用ID',
  `LAST_LOGIN_TIME` datetime(0) NULL DEFAULT NULL COMMENT '最后登录时间',
  `LAST_LOGIN_IP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '127.0.0.1' COMMENT '最后登录IP',
  `LAST_LOGOUT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '最后一次退出时间',
  `RESET_KEY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '重置密码KEY',
  `RESET_PWD` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '重置密码VALUE',
  `LAST_RESET_TIME` datetime(0) NULL DEFAULT NULL COMMENT '上次修改密码时间，最后一次修改密码时间',
  `ERROR_TIME` datetime(0) NULL DEFAULT NULL COMMENT '出错时间',
  `ERROR_COUNT` int(0) NOT NULL DEFAULT 0 COMMENT '出错数量',
  `ERROR_IP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '出错IP',
  `LOCK_TIME` datetime(0) NULL DEFAULT NULL COMMENT '锁定时间',
  `ACTIVATION` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否激活0否1是，是否需要更改密码0否1是',
  `ACTIVATION_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '激活代码',
  `PRIORITY` int(0) NULL DEFAULT 10 COMMENT '排序',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `LAST_TIME` timestamp(0) NULL DEFAULT NULL COMMENT '最后时间',
  `DEL_FLAG` int(0) NULL DEFAULT 0 COMMENT '删除标记0正常1已删除2应用内受限3回收站',
  `DELETE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '删除时间，过期日期',
  `DESCRIPTION` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '描述',
  `SPARE1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用1外部ID，第三方的平台的用户名，如随申办统一身份体系的用户名，微信UNIONID',
  `SPARE2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用2外部ID，第三方用户ID，OpenId',
  PRIMARY KEY (`USER_ID`) USING BTREE,
  INDEX `IDX_BASE_USER_USERNAME`(`USERNAME`) USING BTREE,
  INDEX `IDX_BASE_USER_MOBILE`(`MOBILE`) USING BTREE,
  INDEX `IDX_BASE_USER_EMAIL`(`EMAIL`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '基础用户' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for BASE_USER_EXT
-- ----------------------------
DROP TABLE IF EXISTS `BASE_USER_EXT`;
CREATE TABLE `BASE_USER_EXT`  (
  `USER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户ID',
  `NICKNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户昵称',
  `ID_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '真实姓名，加密的姓名',
  `ID_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '证件类型',
  `ID_NUM` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '身份证号码，加密的身份证号码',
  `ID_MOBILE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '加密的电话号码',
  `NAME_PY` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '姓名全拼',
  `SNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '姓名缩写，外部输入填写的姓名',
  `NAME_EN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '姓名英文',
  `SEARCH_CODE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '查询码，名称的拼音首字母',
  `SEX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '性别GB_XBDM',
  `BIRTHDAY` datetime(0) NULL DEFAULT NULL COMMENT '出生日期',
  `POST_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '家庭邮政编码',
  `ADDRESS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '地址',
  `NATIVE_PLACE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT ' 籍贯GB_XZQHDM_SHENG',
  `FAMILY_ADDRESS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '家庭地址',
  `HOME_TEL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '住宅电话',
  `QQ_NO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '即时通讯QQ号码',
  `WEIXIN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '微信用户名',
  `WEIBO_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '微博用户名',
  `SPARE_MOBILE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用手机，紧急手机',
  `IS_MOBILE_CONFIRM` tinyint(1) NULL DEFAULT NULL COMMENT '手机号码是否验证0否1是',
  `EMERGENCE_PHONE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '紧急电话，外部输入填写的身份证号码，外部导入或临时处理的身份证号码',
  `KEYWORDS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '关键字',
  `INTRO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '个人介绍',
  `COMEFROM` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '来自',
  `IMAGE_PATH` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户图像图标',
  `USER_SIGNATURE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户签名',
  `IP_RANGE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '登录IP地址(\";\"分隔）',
  `MAC_CODE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '允许登录MAC地址(\";\"分隔）',
  `RESUME` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '简历',
  `SPARE1` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用1',
  `SPARE2` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用2',
  `SPARE3` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用3',
  `SPARE4` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用4',
  PRIMARY KEY (`USER_ID`) USING BTREE,
  INDEX `IDX_BASE_USER_EXT_NAME`(`ID_NAME`) USING BTREE,
  INDEX `IDX_BASE_USER_EXT_ID_NUM`(`ID_NUM`) USING BTREE,
  INDEX `IDX_BASE_USER_EXT_ADDR`(`ADDRESS`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '基础用户扩展信息' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for THIRD_MEMBER
-- ----------------------------
DROP TABLE IF EXISTS `THIRD_MEMBER`;
CREATE TABLE `THIRD_MEMBER`  (
  `MEMBER_ID` bigint(0) NOT NULL COMMENT '主键ID',
  `USER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户ID',
  `ORGAN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '机构ID',
  `FOREIGN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '外键ID，人口库ID',
  `ACCOUNT_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '身份提供商ID',
  `SERVER_TYPE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '开放平台认证平台类型',
  `UNION_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '三方全局D',
  `OPEN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '开放平台ID',
  `EMAIL` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '邮箱',
  `AREA_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '手机号对应的国家号',
  `MOBILE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '电话号码',
  `NICK_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '昵称',
  `AVATAR_URL` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '头像',
  `ADDITION_INFO` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '附加信息',
  `CREATOR_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建人ID',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `LAST_TIME` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
  `DEL_FLAG` int(0) NULL DEFAULT NULL COMMENT '删除标记，0未删除1已删除',
  `DESCRIPTION` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `SPARE1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用1',
  `SPARE2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用2',
  PRIMARY KEY (`MEMBER_ID`) USING BTREE,
  INDEX `AK_UK_THIRD_MEMBER_USER_ID`(`USER_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '第三方用户' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for THIRD_MEMBER_BIND
-- ----------------------------
DROP TABLE IF EXISTS `THIRD_MEMBER_BIND`;
CREATE TABLE `THIRD_MEMBER_BIND`  (
  `BIND_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '主键ID',
  `MEMBER_ID` bigint(0) NOT NULL COMMENT '会员ID',
  `USER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户ID',
  `USERNAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '0' COMMENT '系统用户名，手机号',
  `ACCOUNT_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '身份提供商ID',
  `ACCOUNT_KEY` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '第三方账号KEY，市民云、微信等的UnionId或OpenId',
  `BIND_TIME` datetime(0) NULL DEFAULT NULL COMMENT '绑定时间',
  `ADDITION_INFO` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '附加信息',
  `CREATOR_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建人ID',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `LAST_TIME` datetime(0) NULL DEFAULT NULL COMMENT '修改时间',
  `DEL_FLAG` int(0) NULL DEFAULT NULL COMMENT '删除标记，0未删除1已删除',
  `DESCRIPTION` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `SPARE1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用1',
  `SPARE2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用2',
  PRIMARY KEY (`BIND_ID`) USING BTREE,
  INDEX `UK_USER_IDP_BIND`(`USER_ID`, `ACCOUNT_ID`, `ACCOUNT_KEY`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '用户身份提供商绑定' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for THIRD_MEMBER_TOKEN
-- ----------------------------
DROP TABLE IF EXISTS `THIRD_MEMBER_TOKEN`;
CREATE TABLE `THIRD_MEMBER_TOKEN`  (
  `MEMBER_ID` bigint(0) NOT NULL COMMENT '主键ID',
  `USER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户ID',
  `TOKEN` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '令牌TOKEN',
  `FOREIGN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '前台应用或站点ID',
  `USERNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户名',
  `LOGIN_IP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '登录IP',
  `UPDATE_TIME` datetime(0) NOT NULL COMMENT '更新时间',
  `EXPIRE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '过期时间',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `DESCRIPTION` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`MEMBER_ID`) USING BTREE,
  INDEX `AK_UK_THIRD_MEMBER_TOKEN`(`TOKEN`) USING BTREE,
  INDEX `AK_UK_THIRD_MEMBER_USERNAME`(`USERNAME`) USING BTREE,
  INDEX `IDX_THIRD_MEMBER_T_TOKEN`(`TOKEN`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '会员用户令牌' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
