/*

 Source Server         : LLDB
 Source Server Type    : MySQL
 Source Server Version : 80022
 Source Host           : localhost:3306
 Source Schema         : framedb_1.1

 Target Server Type    : MySQL
 Target Server Version : 80022
 File Encoding         : 65001

 Date: 13/10/2025 16:08:47
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for BASE_USER
-- ----------------------------
DROP TABLE IF EXISTS `BASE_USER`;
CREATE TABLE `BASE_USER`  (
  `USER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户ID',
  `XZQH_ID` bigint(20) NULL DEFAULT NULL COMMENT '行政区划编号，用户来源地',
  `SOURCE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '创建来源类型，身份源ID',
  `CREATE_TYPE` int(10) NULL DEFAULT 1 COMMENT '创建方式，数据来源：0导入1录入2授权',
  `USERNAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户名，城市APP的用户名',
  `MOBILE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '手机号码',
  `EMAIL` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '电子邮箱',
  `PASSWORD` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '密码',
  `SALT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '混淆字符',
  `SRC_CODE` int(10) NOT NULL DEFAULT 1 COMMENT '当前来源0缺省1:WEB或PC,2APP21:AndroidAPP,22:IOSAPP,3WAP,4MINI',
  `REGISTER_TIME` datetime(0) NOT NULL COMMENT '注册时间',
  `REGISTER_IP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '127.0.0.1' COMMENT '注册IP',
  `LOGIN_COUNT` int(10) NOT NULL DEFAULT 0 COMMENT '登录次数',
  `CURRENT_LOGIN_TIME` datetime(0) NULL DEFAULT NULL COMMENT '当前登录时间',
  `CURRENT_LOGIN_IP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '127.0.0.1' COMMENT '当前登录IP',
  `LAST_APP_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '最后登录的应用ID',
  `LAST_LOGIN_TIME` datetime(0) NULL DEFAULT NULL COMMENT '最后登录时间',
  `LAST_LOGIN_IP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT '127.0.0.1' COMMENT '最后登录IP',
  `LAST_LOGOUT_TIME` datetime(0) NULL DEFAULT NULL COMMENT '最后一次退出时间',
  `RESET_KEY` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '重置密码KEY',
  `RESET_PWD` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '重置密码VALUE',
  `LAST_RESET_TIME` datetime(0) NULL DEFAULT NULL COMMENT '上次修改密码时间，最后一次修改密码时间',
  `ERROR_TIME` datetime(0) NULL DEFAULT NULL COMMENT '出错时间',
  `ERROR_COUNT` int(10) NOT NULL DEFAULT 0 COMMENT '出错数量',
  `ERROR_IP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '出错IP',
  `LOCK_TIME` datetime(0) NULL DEFAULT NULL COMMENT '锁定时间',
  `ACTIVATION` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否激活0否1是，是否需要更改密码0否1是',
  `ACTIVATION_CODE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '激活代码',
  `PRIORITY` int(10) NULL DEFAULT 10 COMMENT '排序',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `LAST_TIME` timestamp(0) NULL DEFAULT NULL COMMENT '最后时间',
  `DEL_FLAG` int(10) NULL DEFAULT 0 COMMENT '删除标记0正常1已删除2应用内受限3回收站',
  `DELETE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '删除时间，过期日期',
  `DESCRIPTION` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '描述',
  `SPARE1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用1外部ID，第三方的平台的用户名，如随申办统一身份体系的用户名，微信UNIONID',
  `SPARE2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用2外部ID，第三方用户ID，OpenId',
  PRIMARY KEY (`USER_ID`) USING BTREE,
  INDEX `IDX_BASE_USER_USERNAME`(`USERNAME`) USING BTREE,
  INDEX `IDX_BASE_USER_MOBILE`(`MOBILE`) USING BTREE,
  INDEX `IDX_BASE_USER_EMAIL`(`EMAIL`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '基础用户' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for BASE_USER_EXT
-- ----------------------------
DROP TABLE IF EXISTS `BASE_USER_EXT`;
CREATE TABLE `BASE_USER_EXT`  (
  `USER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户ID',
  `NICKNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户昵称',
  `ID_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '真实姓名，加密的姓名',
  `ID_TYPE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '证件类型',
  `ID_NUM` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '身份证号码，加密的身份证号码',
  `ID_MOBILE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '加密的电话号码',
  `NAME_PY` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '姓名全拼',
  `SNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '姓名缩写，外部输入填写的姓名',
  `NAME_EN` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '姓名英文',
  `SEARCH_CODE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '查询码，名称的拼音首字母',
  `SEX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '性别GB_XBDM',
  `BIRTHDAY` datetime(0) NULL DEFAULT NULL COMMENT '出生日期',
  `POST_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '家庭邮政编码',
  `ADDRESS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '地址',
  `NATIVE_PLACE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT ' 籍贯GB_XZQHDM_SHENG',
  `FAMILY_ADDRESS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '家庭地址',
  `HOME_TEL` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '住宅电话',
  `QQ_NO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '即时通讯QQ号码',
  `WEIXIN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '微信用户名',
  `WEIBO_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '微博用户名',
  `SPARE_MOBILE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用手机，紧急手机',
  `IS_MOBILE_CONFIRM` tinyint(1) NULL DEFAULT NULL COMMENT '手机号码是否验证0否1是',
  `EMERGENCE_PHONE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '紧急电话，外部输入填写的身份证号码，外部导入或临时处理的身份证号码',
  `KEYWORDS` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '关键字',
  `INTRO` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '个人介绍',
  `COMEFROM` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '来自',
  `IMAGE_PATH` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户图像图标',
  `USER_SIGNATURE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户签名',
  `IP_RANGE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '登录IP地址(\";\"分隔）',
  `MAC_CODE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '允许登录MAC地址(\";\"分隔）',
  `RESUME` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '简历',
  `SPARE1` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用1',
  `SPARE2` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用2',
  `SPARE3` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用3',
  `SPARE4` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用4',
  PRIMARY KEY (`USER_ID`) USING BTREE,
  INDEX `IDX_BASE_USER_EXT_NAME`(`ID_NAME`) USING BTREE,
  INDEX `IDX_BASE_USER_EXT_ID_NUM`(`ID_NUM`) USING BTREE,
  INDEX `IDX_BASE_USER_EXT_ADDR`(`ADDRESS`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '基础用户扩展信息' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for PUBLIC_MAIL_SEND_RECORD
-- ----------------------------
DROP TABLE IF EXISTS `PUBLIC_MAIL_SEND_RECORD`;
CREATE TABLE `PUBLIC_MAIL_SEND_RECORD`  (
  `SEND_ID` bigint(20) NOT NULL COMMENT '主键ID',
  `APP_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '应用ID',
  `PROVIDER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '邮件提供商ID，平台ID',
  `PROVIDER_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '邮件提供商名称，平台名称',
  `FOREIGN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '外键ID',
  `SENDER_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '发送信息者名称，后台用户则管理员，会员则会员名称，企业会员则号名称',
  `RECEIVER_EMAIL` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '接收人ID，邮箱地址',
  `RECEIVER_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '接收人',
  `BIZ_TYPE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '业务类型',
  `TITLE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '信息标题，主题',
  `CONTENT` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '信息内容',
  `MSG_URL` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '信息链接，链接平台内地址，可点击访问',
  `STATUS` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '信息状态',
  `SEND_TIME` datetime(0) NULL DEFAULT NULL COMMENT '发送时间',
  `SEND_STATUS` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '发送状态(0草稿1已发)',
  `READ_TIME` datetime(0) NULL DEFAULT NULL COMMENT '阅读时间',
  `READ_STATUS` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '信息状态(0未读1已读2全组已读)',
  `CREATOR_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建者ID',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `LAST_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `DEL_FLAG` int(10) NULL DEFAULT 0 COMMENT '删除标记0正常1已删除2应用内受限3回收站',
  `DESCRIPTION` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `SPARE1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用1',
  `SPARE2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用2',
  PRIMARY KEY (`SEND_ID`) USING BTREE,
  INDEX `IDX_PUBLIC_MAIL_S_R_S_NAME`(`SENDER_NAME`) USING BTREE,
  INDEX `IDX_PUBLIC_MAIL_S_R_R_EMAIL`(`RECEIVER_EMAIL`) USING BTREE,
  INDEX `IDX_PUBLIC_MAIL_S_R_STATUS`(`STATUS`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '邮件发送记录' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for PUBLIC_SMS_SEND_RECORD
-- ----------------------------
DROP TABLE IF EXISTS `PUBLIC_SMS_SEND_RECORD`;
CREATE TABLE `PUBLIC_SMS_SEND_RECORD`  (
  `SEND_ID` bigint(20) NOT NULL COMMENT '主键ID',
  `APP_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '应用ID',
  `PROVIDER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '短信提供商ID，平台ID',
  `PROVIDER_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '短信提供商名称，平台名称',
  `FOREIGN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '外键ID',
  `RECEIVER_MOBILE` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '接收人手机号',
  `RECEIVER_NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '接收人',
  `BIZ_TYPE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '消息类型',
  `BIZ_SUBTYPE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '信息子类型',
  `CONTENT` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '信息内容',
  `MSG_URL` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '信息链接，链接平台内地址，可点击访问',
  `STATUS` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '信息状态',
  `SEND_TIME` datetime(0) NULL DEFAULT NULL COMMENT '发送时间',
  `SEND_STATUS` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '发送状态(0草稿1已发)',
  `RETURN_TIME` datetime(0) NULL DEFAULT NULL COMMENT '返回时间',
  `RETURN_INFO` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '返回结果',
  `CREATOR_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建者ID',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `LAST_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `DEL_FLAG` int(10) NULL DEFAULT 0 COMMENT '删除标记0正常1已删除2应用内受限3回收站',
  `DESCRIPTION` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `SPARE1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用1',
  `SPARE2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用2',
  PRIMARY KEY (`SEND_ID`) USING BTREE,
  INDEX `IDX_PUBLIC_MAIL_S_R_S_NAME`(`PROVIDER_NAME`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '短信发送记录' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for PUBLIC_TEMPLATE_INFO
-- ----------------------------
DROP TABLE IF EXISTS `PUBLIC_TEMPLATE_INFO`;
CREATE TABLE `PUBLIC_TEMPLATE_INFO`  (
  `TEMPLATE_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '模板ID',
  `APP_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '应用ID',
  `ORGAN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '机构ID',
  `PROVIDER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '提供商ID，平台ID',
  `PROVIDER_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '提供商名称，平台名称',
  `FOREIGN_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '外键ID',
  `TYPE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板类型，邮件模板，短信模板',
  `SUB_TYPE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板子类型',
  `NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '模板名称，标题名称',
  `SIGNATURE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '签名，发送人名称',
  `CONTENT` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '内容JSON，发布版本的JSON配置',
  `PRIORITY` int(10) NULL DEFAULT NULL COMMENT '排序号',
  `STATUS` int(10) NULL DEFAULT 1 COMMENT '状态0未生效1正常2受限3锁定',
  `CREATOR_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '创建者ID',
  `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `LAST_TIME` datetime(0) NULL DEFAULT NULL COMMENT '更新时间',
  `DEL_FLAG` int(10) NULL DEFAULT 0 COMMENT '删除标记0正常1已删除2应用内受限3回收站',
  `DESCRIPTION` varchar(800) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注',
  `SPARE1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用1',
  `SPARE2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备用2',
  PRIMARY KEY (`TEMPLATE_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '模板信息配置' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
