<?xml version="1.0" encoding="UTF-8"?>
<!--

    module-authn - 动态认证对接模块
    Copyright © 2020-2025 Linlan (open@linlan.net)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.linlan.eframe</groupId>
        <artifactId>module-extend</artifactId>
        <version>1.1.15</version>
    </parent>
    <groupId>net.linlan.eframe</groupId>
    <artifactId>module-authn</artifactId>
    <version>1.1.15</version>
    <packaging>jar</packaging>
    <name>module-authn</name>
    <description>
        动态认证对接模块
    </description>
    <properties>
        <tencentcloud.sdk.sms.version>3.1.998</tencentcloud.sdk.sms.version>
        <qiniu.version>7.2.28</qiniu.version>
    </properties>
    <url>https://gitee.com/linlannet/eframe-java-backend.git</url>
    <licenses>
        <license>
            <name>Apache-2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <scm>
        <url>https://gitee.com/linlannet/eframe-java-backend/tree/master/module-authn</url>
        <connection>scm:git:git://gitee.com/linlannet/eframe-java-backend.git</connection>
    </scm>
    <developers>
        <developer>
            <id>linlan</id>
            <name>linlan info</name>
            <email>linlannet@163.com</email>
            <organization>Linlan Corporation</organization>
            <roles>
                <role>Member</role>
            </roles>
            <timezone>Asia/Beijing</timezone>
        </developer>
    </developers>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-freemarker</artifactId>
        </dependency>
        <!--阿里云邮件sdk-->
        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>dm20151123</artifactId>
            <version>1.0.6</version>
        </dependency>
        <!-- 腾讯云邮件sdk -->
        <dependency>
            <groupId>com.tencentcloudapi</groupId>
            <artifactId>tencentcloud-sdk-java-ses</artifactId>
            <version>3.1.944</version>
            <exclusions>
                <exclusion>
                    <groupId>com.tencentcloudapi</groupId>
                    <artifactId>tencentcloud-sdk-java-common</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.6.2</version>
        </dependency>
        <!--阿里云邮件sdk-->
        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>dm20151123</artifactId>
            <version>1.0.6</version>
        </dependency>
        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>dysmsapi20170525</artifactId>
            <version>2.0.23</version>
        </dependency>
        <dependency>
            <groupId>com.tencentcloudapi</groupId>
            <artifactId>tencentcloud-sdk-java-sms</artifactId>
            <version>${tencentcloud.sdk.sms.version}</version>
        </dependency>
        <dependency>
            <groupId>com.qiniu</groupId>
            <artifactId>qiniu-java-sdk</artifactId>
            <version>${qiniu.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.gson</groupId>
                    <artifactId>gson</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.qiniu</groupId>
                    <artifactId>happy-dns-java</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.httpcomponents</groupId>
                    <artifactId>httpclient</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.28</version>
        </dependency>
        <!-- 通用工具-->
        <dependency>
            <groupId>net.linlan.eframe</groupId>
            <artifactId>eframe-api</artifactId>
        </dependency>


    </dependencies>

</project>
